-- The production schema is versioned under database/migrations/.
--
-- Apply every migration in lexical order. This file intentionally contains no
-- executable DDL so that it cannot drift from the migration history.
-- See database/README.md for local and Supabase deployment instructions.
